config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :artists

  post "/account-session", to: "stripe#account_session", as: :onboarding_session
  post "/stripe/webhooks", to: "stripe#webhooks"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  authenticated :artist do
    root "artists#dashboard", as: :authenticated_artist_root
    resources :songs
    resource :dashboard, to: "artists#dashboard"
  end

  authenticated :user do
    root "music#show", as: :authenticated_user_root
  end

  resource :music, only: [ :show ], controller: :music do
    post "audio_player", to: "music#audio_player", on: :collection
  end

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artist.rb
class Artist < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :songs

  after_create_commit :create_stripe_account

  enum :stripe_status, [ "awaiting_onboarding", "payouts_enabled" ]

  def create_stripe_account
    stripe_account = Stripe::Account.create()
    update(stripe_account_id: stripe_account.id)
  end
end

app/models/song.rb
class Song < ApplicationRecord
  belongs_to :artist
  has_one_attached :image
  has_one_attached :audio_file
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/webhook_event.rb
class WebhookEvent < ApplicationRecord
  serialize :data, coder: JSON
  enum :status, [ "pending", "failed", "processed" ]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    # Permit the `subscribe_newsletter` parameter along with the other
    # sign up parameters.
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :stage_name ])
    devise_parameter_sanitizer.permit(:account_update, keys: [ :stage_name ])
  end
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  def dashboard
    # if current_artist.payouts_enabled?
    #   @balance ||= Stripe::Balance.retrieve({stripe_account: current_artist.stripe_account_id })
    # end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/music_controller.rb
class MusicController < ApplicationController
  def show
    @songs = Song.all
  end
  def audio_player
    @song = Song.find(params[:song_id])
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :authenticate_artist!
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = current_artist.songs.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = current_artist.songs.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to @song, notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to @song, notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy!

    respond_to do |format|
      format.html { redirect_to songs_path, status: :see_other, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = current_artist.songs.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :image, :audio_file, :artist_id)
    end
end

app/controllers/stripe_controller.rb
class StripeController < ApplicationController
  skip_before_action :verify_authenticity_token, only: [ :webhooks ]
  before_action :auth_webhook_request, only: [ :webhooks ]

  def account_session
    account_session = Stripe::AccountSession.create({
      account: current_artist.stripe_account_id,
      components: {
        account_onboarding: {
          enabled: true,
          features: { external_account_collection: true }
        }
      }
    })

    render json: { client_secret: account_session.client_secret }
  end

  def webhooks
    @webhook_event = WebhookEvent.create(source: :stripe, data: @event)
    @artist = Artist.find_by_stripe_account_id(@event.account)
    case @event.type
    when "account.updated"
      if @event["data"]["object"]["payouts_enabled"] == true
        @artist.payouts_enabled!
      end
    else
        puts "Unhandled event type: #{@event.type}"
    end
    @webhook_event.processed!
  end

  private

  def auth_webhook_request
    payload = request.body.read
    sig_header = request.env["HTTP_STRIPE_SIGNATURE"]

    begin
        @event = Stripe::Webhook.construct_event(
            payload, sig_header, Rails.application.credentials.dig(:stripe, :wh_secret)
        )
    rescue JSON::ParserError => e
        # Invalid payload
        status 400
        nil
    rescue Stripe::SignatureVerificationError => e
        # Invalid signature
        status 400
        nil
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/helpers/stripe_helper.rb
module StripeHelper
end

app/views/artists/dashboard.html.erb
<div class="w-full min-h-screen pt-28 flex justify-center">
  <div class="max-w-5xl w-full flex flex-col items-center text-center">
    <h1 class="text-5xl text-gray-100"> Welcome to the Artist Dashboard </h1>
    <div class="flex gap-4 mt-8">
      <%= link_to "Post a song", new_song_path, class: "p-2 rounded-lg bg-purple-500 text-purple-100" %>
      <%= link_to "View your songs", songs_path, class: "p-2 rounded-lg bg-blue-500 text-blue-100" %>
      <%= link_to "edit your account", edit_artist_registration_path, class: "p-2 rounded-lg bg-green-500 text-green-100" %>
      <%= link_to "Sign out", destroy_artist_session_path, class: "p-2 rounded-lg bg-pink-500 text-pink-100", data: { turbo_method: :delete }  %>

      <% if current_artist.payouts_enabled? %>
        <span class="bg-gradient-to-r from-green-600 to-blue-400 text-green-100 p-2 rounded-full"> 💰 Payments Enabled </span>
      <% end %>
    </div>

    <br/>

     <% if current_artist.payouts_enabled? %>
      <div class="flex flex-col items-center justify-center h-56 w-1/2 bg-gray-100 rounded-lg shadow-lg pb-8">
        <p> Your current balance ( Payouts happen daily ) </p>
        <p class="text-5xl font-bold bg-clip-text text-transparent bg-gradient-to-r from-pink-500 to-purple-400"> <%= number_to_currency(@balance.available[0].amount / 100) %> </p>
      </div>
    <% else %>
      <div data-controller="stripe-onboarding" data-stripe-onboarding-url-value="<%= onboarding_session_path %>" class="bg-gray-100 w-80"> </div>
    <% end %>
    
  </div>
</div>

app/views/home/index.html.erb
<div class="w-full min-h-screen bg-gradient-to-b from-blue-800 to-purple-300 flex flex-col items-center pt-36">
  <h1 class="font-bold text-7xl text-blue-200">Spotify-Rails</h1>
  <p class="text-2xl bg-clip-text text-transparent bg-gradient-to-r from-pink-500 via-green-500 via-30% to-yellow-500 mt-2">The new best music streaming platform that pays fairly!</p>
  <div class="h-36 flex items-center justify-center">
    <%= link_to music_path do %>
      <%= image_tag "play.png", class: "w-20 object-cover hover:bg-pink-500 rounded-full overflow-hidden duration-300	" %>
    <% end %>
  </div>
  <div class="grid grid-cols-3 gap-8 max-w-5xl w-full mx-auto">
    <%= image_tag "violin.jpg", class: "h-96 w-full object-cover" %>
    <%= image_tag "dj.jpg", class: "h-96 w-full object-cover" %>
    <%= image_tag "lady.jpg", class: "h-96 w-full object-cover" %>
  </div>

  <br/>

  <%= link_to "Sign up as an artist", new_artist_registration_path, class: "inline-block bg-gradient-to-r from-blue-500 to-purple-600 text-white font-semibold py-2 px-6 rounded-lg shadow-md hover:shadow-lg transform transition-all duration-300 hover:-translate-y-1 hover:bg-gradient-to-r hover:from-blue-600 hover:to-purple-700 mb-4" %>
</div>

app/views/layouts/_alerts.html.erb
<% if notice.present? %>
  <div class="notice-aux fixed">
    <p class="mt-2 ml-2 py-2 px-3 bg-blue-50 mb-5 text-blue-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
  </div>
<% end %>
<% if alert.present? %>
  <div class="notice-aux fixed">
    <p class="mt-2 ml-2 py-2 px-3 bg-orange-50 mb-5 text-orange-500 font-medium rounded-lg inline-block" id="notice"><%= alert %></p>
  </div>
<% end %>
<script>
    function hideNotices() {
    const notices = document.querySelectorAll('.notice, .alert, .notice-aux');
    notices.forEach(function(notice) {
        setTimeout(function() {
        notice.style.display = 'none';
        }, 2000); // Oculta el elemento después de 3000 milisegundos (3 segundos)
    });
    }

    document.addEventListener("turbo:load", function() {
    hideNotices(); // Llama a la función para ocultar las alertas al cargar
    });

    // También llamamos a la función al cargar la página inicialmente
    document.addEventListener("DOMContentLoaded", function() {
    hideNotices();
    });
</script>

app/views/layouts/_navbar.html.erb
<div class="w-full h-14 fixed top-0 bg-indigo-900">
  <div class="max-w-5xl w-full mx-auto px-8 h-full flex justify-between items-center">
    <%= link_to "Home", "/music", class: "text-lg text-white" %>
    <div class="flex gap-4 h-full items-center">
      <% if current_user %>
        <div class="relative" data-controller="dropdown" data-action="click@window->dropdown#closeIfOutside">
          <%= link_to "#", data: { action: "dropdown#toggle" } do %>
            <div class="w-8 h-8 rounded-full bg-indigo-700 p-1"> 
              <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-full text-white">
                <path stroke-linecap="round" stroke-linejoin="round" d="M15.75 6a3.75 3.75 0 1 1-7.5 0 3.75 3.75 0 0 1 7.5 0ZM4.501 20.118a7.5 7.5 0 0 1 14.998 0A17.933 17.933 0 0 1 12 21.75c-2.676 0-5.216-.584-7.499-1.632Z" />
              </svg>
            </div>
          <% end %>

          <div class="w-40 bg-gray-400 rounded-lg absolute top-10 hidden flex flex-col items-center justify-between p-2" data-dropdown-target="menu"> 
            <%= link_to "Settings", edit_user_registration_path, class: "text-xl text-white" %>
            <div class="w-full h-[1.5px] bg-white my-4"></div>
            <%= link_to "Sign out", destroy_user_session_path, class: "bg-red-500 text-red-50 p-2 rounded-lg", data: { turbo_method: :delete } %>
          </div>
        </div>
      <% else %>
        <%= link_to "Sign in", new_user_session_path, class: "text-white" %>
        <%= link_to "Create account", new_user_registration_path, class: "bg-gray-500 p-2 text-gray-50 rounded-lg" %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Spotify Rails" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="stripe-pk" content="<%= Rails.application.credentials.dig(:stripe, :pk) %>">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="bg-gradient-to-b from-blue-800 to-purple-300">
    <%= render "layouts/navbar" if !current_artist %>
    <%= render "layouts/alerts" %>
    <%= yield %>
    <div id="audio-player-id" class="fixed bottom-0 w-full">
    </div>
  </body>
</html>

app/views/music/_audio_player.html.erb
<div class="h-20 w-full bg-gray-700 flex items-center justify-center gap-4 relative" data-controller="audio-player" data-action="music:toggled@window->audio-player#updatePlayButton">
  <%= link_to "", data: { action: "audio-player#closeSong" }, class: "absolute top-2 right-2 bg-red-500 rounded-full h-6 w-6 flex items-center justify-center hover:bg-red-600" do %>
    <svg xmlns="http://www.w3.org/2000/svg" class="h-4 w-4 text-white font-bold" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
      <line x1="18" y1="6" x2="6" y2="18" />
      <line x1="6" y1="6" x2="18" y2="18" />
    </svg>
    <span class="sr-only">Close</span>
  <% end %>
  <%= image_tag(song.image, class: "w-20 h-full object-cover p-2") %>
  <div>
    <p class="text-lg text-white"> <%= song.title %> </p>
    <p class="text-xs text-white"> <%= song.artist.stage_name %> </p>
  </div>
  
  <%= link_to "", data: { action: "audio-player#toggle" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 fill-indigo-100 hover:fill-indigo-500" data-audio-player-target="play">
      <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm14.024-.983a1.125 1.125 0 0 1 0 1.966l-5.603 3.113A1.125 1.125 0 0 1 9 15.113V8.887c0-.857.921-1.4 1.671-.983l5.603 3.113Z" clip-rule="evenodd" />
    </svg>

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 fill-indigo-100 hover:fill-indigo-500 hidden" data-audio-player-target="pause">
      <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12ZM9 8.25a.75.75 0 0 0-.75.75v6c0 .414.336.75.75.75h.75a.75.75 0 0 0 .75-.75V9a.75.75 0 0 0-.75-.75H9Zm5.25 0a.75.75 0 0 0-.75.75v6c0 .414.336.75.75.75H15a.75.75 0 0 0 .75-.75V9a.75.75 0 0 0-.75-.75h-.75Z" clip-rule="evenodd" />
    </svg>
  <% end %>

  <div class="flex text-white">
    <span data-audio-player-target="currentTime"> 00:00 </span>
    /
    <span data-audio-player-target="duration"> 00:00 </span>
  </div>
  <input type="range" class="max-w-2xl w-full" data-audio-player-target="range" data-action="change->audio-player#currentTimeUpdated"/>
</div>

app/views/music/_play.html.erb
<div data-controller="music" data-music-url-value="<%= rails_blob_url(song.audio_file) %>"
     data-music-audio-player-url-value="<%= audio_player_music_path(song_id: song.id) %>"
     data-action="audio-player-switched@window->music#audioChanged audio-player:toggled@window->music#audioToggled">
  <%= link_to "", data: { action: "music#toggle" } do %>
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 fill-indigo-100 hover:fill-indigo-500" data-music-target="play">
      <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12Zm14.024-.983a1.125 1.125 0 0 1 0 1.966l-5.603 3.113A1.125 1.125 0 0 1 9 15.113V8.887c0-.857.921-1.4 1.671-.983l5.603 3.113Z" clip-rule="evenodd" />
    </svg>

    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="currentColor" class="w-10 fill-indigo-100 hover:fill-indigo-500 hidden" data-music-target="pause">
      <path fill-rule="evenodd" d="M2.25 12c0-5.385 4.365-9.75 9.75-9.75s9.75 4.365 9.75 9.75-4.365 9.75-9.75 9.75S2.25 17.385 2.25 12ZM9 8.25a.75.75 0 0 0-.75.75v6c0 .414.336.75.75.75h.75a.75.75 0 0 0 .75-.75V9a.75.75 0 0 0-.75-.75H9Zm5.25 0a.75.75 0 0 0-.75.75v6c0 .414.336.75.75.75H15a.75.75 0 0 0 .75-.75V9a.75.75 0 0 0-.75-.75h-.75Z" clip-rule="evenodd" />
    </svg>
  <% end %>
</div>

app/views/music/audio_player.turbo_stream.erb
<%= turbo_stream.update("audio-player-id") do %>
  <%= render "audio_player", song: @song %>
<% end %>

app/views/music/show.html.erb
<div class="min-h-screen w-full bg-gray-900 pb-36">
  <div class="max-w-5xl w-full mx-auto p-8 grid md:grid-cols-4 gap-8"> 
    <% @songs.each do |song| %>
      <div class="w-full "> 
        <%= image_tag(song.image, class: "h-96 md:h-40 w-full object-cover rounded-lg") %>
        <div class="flex justify-between">
          <div class="flex flex-col">
            <p class="text-xl text-gray-100"> <%= song.title %> </p>
            <p class="text-sm text-gray-200"> <%= song.artist.stage_name %> </p>
          </div>
          <%= render "play", song: song %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/songs/_form.html.erb
<%= form_with(model: song, class: "contents") do |form| %>
  <% if song.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-lg mt-3">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :title %>
    <%= form.text_field :title, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :image %>
    <%= form.file_field :image, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="my-5">
    <%= form.label :audio_file %>
    <%= form.file_field :audio_file, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
  </div>
<% end %>

app/views/songs/_song.html.erb
<div id="<%= dom_id song %>">
  <p class="my-5">
    <strong class="block font-medium mb-1">Title:</strong>
    <%= song.title %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Image:</strong>
    <%= link_to song.image.filename, song.image if song.image.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Audio file:</strong>
    <%= link_to song.audio_file.filename, song.audio_file if song.audio_file.attached? %>
  </p>

  <p class="my-5">
    <strong class="block font-medium mb-1">Artist:</strong>
    <%= song.artist_id %>
  </p>

</div>

app/views/songs/edit.html.erb
<div class="mx-auto md:w-2/3 w-full">
  <h1 class="font-bold text-4xl">Editing song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Show this song", @song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/index.html.erb
<div class="w-full md:w-2/3 mx-auto min-h-screen pt-20">

  <% content_for :title, "Songs" %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl">Songs</h1>
    <%= link_to "New song", new_song_path, class: "rounded-lg py-3 px-5 bg-blue-600 text-white block font-medium" %>
  </div>

  <div id="songs" class="min-w-full">
    <% @songs.each do |song| %>
      <%= render song %>
      <p>
        <%= link_to "Show this song", song, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
      </p>
    <% end %>
  </div>
</div>

app/views/songs/new.html.erb
<div class="mx-auto md:w-2/3 w-full min-h-screen pt-16">
  <h1 class="font-bold text-4xl">New song</h1>

  <%= render "form", song: @song %>

  <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
</div>

app/views/songs/show.html.erb
<div class="mx-auto md:w-2/3 w-full flex min-h-screen pt-12">
  <div class="mx-auto">
    <%= render @song %>

    <%= link_to "Edit this song", edit_song_path(@song), class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <%= link_to "Back to songs", songs_path, class: "ml-2 rounded-lg py-3 px-5 bg-gray-100 inline-block font-medium" %>
    <div class="inline-block ml-2">
      <%= button_to "Destroy this song", @song, method: :delete, class: "mt-2 rounded-lg py-3 px-5 bg-gray-100 font-medium" %>
    </div>
  </div>
</div>